/// Flutter icons Newiconproject
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Newiconproject
///      fonts:
///       - asset: fonts/Newiconproject.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Newiconproject {
  Newiconproject._();

  static const _kFontFam = 'Newiconproject';
  static const String? _kFontPkg = null;

  static const IconData event = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData indonesia = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData license_plate_8154394 = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
